# If there are words that you think should not be treated as typo.
# Please list here along with a comment.

[default]
extend-ignore-re = [
    "(?Rm)^.*(#|//)\\s*typos:disable-line$",
    "(#|//)\\s*typos:ignore-next-line\\n.*",
    "(?s)(#|//)\\s*typos:off.*?\\n\\s*(#|//)\\s*typos:on",
]

[default.extend-words]
typ = "typ"
pendings = "pendings"

[default.extend-identifiers]

[files]
extend-exclude = [
    "**/Cargo.toml",
]
